#ifndef _CPU_H_
#define _CPU_H_
#include <MainBus.h>

class CPU {
    public:

        enum InterruptType
        {
            IRQ,   /* Maskable interrupts (aka IRQs) can be generated by external circuitry on the cart  */
            NMI,   /* NES uses non-maskable interrupts (NMIs) generated by PPU in the end of each frame (so-called VBlank interrupts).  */
            BRK_   /* Break */
        };
        /* CPU 连接总线 */
        CPU(MainBus &mem);

        void Reset();
        void Reset(Address start_address);
        void SkipDMACycles();
        void Step();
        Address GetPC() { return r_PC; }
        void Interrupt(InterruptType type);
    private:
        /* 根据src/CPU.cpp中用到的函数或成员变量，请自行补全此处私有成员*/
        // 请补全
        

};

#endif 